[default]
Library=Policar New 1:32 - Borders
Scale=1:32
Unit=cm
Logo=policar.jpg

[P051]
Name=R1 Inner border
Shape=curve,2.9,6,45
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=e,niborder1,c,1,-1,45,2.9,6,1

[P053]
Name=R1 Outer border
Shape=curve,26.85,-6.0,45
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P052]
Name=R2 Inner border
Shape=curve,20.85,6,45
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P054]
Name=R2 Outer border
Shape=curve,44.75,-6.0,45
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P057]
Name=R3 Inner border
Shape=curve,38.75,6,22.5
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P058]
Name=R3 Outer border
Shape=curve,62.65,-6,22.5
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P055]
Name=R4 Inner border
Shape=curve,56.65,6,22.5
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P056]
Name=R4 Outer border
Shape=curve,80.55,-6,22.5
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P002]
Name=17.9cm Straight Border
Shape=6.00,17.90
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P061]
Name= 6.14cm Straight Border
Shape=6.00,6.14
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P059]
Name=End left border
Shape=pie,6,-10
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

[P060]
Name=End right border
Shape=pie,6,10
ColorCoding=8421504
Texture1=f,200,200,200
Texture2=

