[default]
Library=Policar New 1:32 - Borders
Scale=1:32
Unit=cm
Logo=policar.jpg

[2xP051]
Name=R1 Inner border
Shape=curve,2.95,6,45.0
Equivalent=P051/2;
ColorCoding=8421504
Texture1=f,0,0,0

[2xP053]
Name=R1 Outer border
Shape=curve,26.85,-6.0,45.0
Equivalent=P053/2;
ColorCoding=8421504
Texture1=f,0,0,0

[2xP052]
Name=R2 Inner border
Shape=curve,20.85,6,45.0
Equivalent=P052/2;
ColorCoding=8421504
Texture1=f,0,0,0

[2xP054]
Name=R2 Outer border
Shape=curve,44.75,-6.0,45.0
Equivalent=P054/2;
ColorCoding=8421504
Texture1=f,0,0,0

[P055]
Name=R3 Inner border
Shape=curve,38.75,6,22.5
ColorCoding=8421504
Texture1=f,0,0,0

[P056]
Name=R3 Outer border
Shape=curve,62.65,-6,22.5
ColorCoding=8421504
Texture1=f,0,0,0

[P057]
Name=R4 Inner border
Shape=curve,56.65,6,22.5
ColorCoding=8421504
Texture1=f,0,0,0

[P058]
Name=R4 Outer border
Shape=curve,80.55,-6,22.5
ColorCoding=8421504
Texture1=f,0,0,0

[P071]
Name=R5 Inner border
Shape=curve,74.55,6,22.5
ColorCoding=8421504
Texture1=f,0,0,0

[P072]
Name=R5 Outer border
Shape=curve,98.45,-6,22.5
ColorCoding=8421504
Texture1=f,0,0,0

[2xP002]
Name=35.8cm Straight Border
Shape=6.00,35.8
Equivalent=P002/2;
ColorCoding=8421504
Texture1=f,0,0,0

[P002]
Name=17.9cm Straight Border
Shape=6.00,17.90
ColorCoding=8421504
Texture1=f,0,0,0

[P061]
Name= 6.14cm Straight Border
Shape=6.00,6.14
ColorCoding=8421504
Texture1=f,0,0,0

[P059]
Name=End left border
Shape=pie,6,-10
ColorCoding=8421504
Texture1=f,0,0,0

[P060]
Name=End right border
Shape=pie,6,10
ColorCoding=8421504
Texture1=f,0,0,0


[P051]
Name=R1 Half Inner border
Shape=curve,2.95,6,22.5
ColorCoding=8421504
Texture1=f,0,0,0

[P053]
Name=R1 Half Outer border
Shape=curve,26.85,-6.0,22.5
ColorCoding=8421504
Texture1=f,0,0,0

[P052]
Name=R2 Half Inner border
Shape=curve,20.85,6,22.5
ColorCoding=8421504
Texture1=f,0,0,0

[P054]
Name=R2 Half Outer border
Shape=curve,44.75,-6.0,22.5
ColorCoding=8421504
Texture1=f,0,0,0

